on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
      
        #- name: ðŸ”¨ Build Project
        #run: |
        #npm install
        #npm run build

    - name: Clean ReactJS precache-manifest and logs
      uses: StephanThierry/ftp-delete-action@releases/v1
      with:
        host: rash.xsrv.jp
        user: rash
        password: ${{ secrets.ftp_password }}
        remoteFiles: "precache-manifest.*.js;logs/*.log"
        workingDir: rash.xsrv.jp/public_html/
        ignoreSSL: "1"

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: rash.xsrv.jp
        username: rash 
        password: ${{ secrets.ftp_password }}
        server-dir: rash.xsrv.jp/public_html/
        local-dir: ./build/


